name: BannedBlockPlus
version: '1.1.1'
main: me.zombieman.bannedblockplus.BannedBlockPlus
api-version: '1.16'
commands:
  addbannedblocks:
    aliases:
      - addblocks
  removebannedblocks:
    aliases:
      - removeblocks
  checkbannedblocks:
    aliases:
      - checkblocks
  bypassbannedblocks:
    aliases:
      - bypassblocks
  listbannedblocks:
    aliases:
      - listblocks
  toggleaddbannedblocks:
    aliases: [togglebannedblocksadder, toggleaddbannedblocks]