name: BannedBlockPlus
version: '1.4.0'
main: me.zombieman.bannedblockplus.BannedBlockPlus
api-version: '1.16'
commands:
  addbannedblocks:
    aliases:
      - addblocks
  removebannedblocks:
    aliases:
      - removeblocks
  checkbannedblocks:
    aliases:
      - checkblocks
  bypassbannedblocks:
    aliases:
      - bypassblocks
  listbannedblocks:
    aliases:
      - listblocks
  reloadbannedblocksconfig:
    aliases:
      - reloadconfig
  clearlistofbannedblocks:
    aliases:
      - clearbannedblocks
      - clearblocks
  toggleaddbannedblocks:
    aliases: [togglebannedblocksadder, toggleaddbannedblocks]