name: BannedBlockPlus
version: '1.6.2'
main: me.zombieman.bannedblockplus.BannedBlockPlus
api-version: '1.16'
authors: [zombieman]
commands:
  addbannedblocks:
    aliases:
      - addblocks
  addallblocks:
    aliases:
      - addall
  removebannedblocks:
    aliases:
      - removeblocks
  checkbannedblocks:
    aliases:
      - checkblocks
  bypassbannedblocks:
    aliases:
      - bypassblocks
  listbannedblocks:
    aliases:
      - listblocks
  reloadbannedblocksconfig:
    aliases:
      - reloadconfig
  clearlistofbannedblocks:
    aliases:
      - clearbannedblocks
      - clearblocks
  toggleaddbannedblocks:
    aliases: [togglebannedblocksadder, toggleaddbannedblocks]